bash commands/runWith1Slices.sh
bash commands/runWith2Slices.sh
bash commands/runWith3Slices.sh
bash commands/runWith5Slices.sh
bash commands/runWith10Slices.sh
bash commands/runWith50Slices.sh
bash commands/runWith100Slices.sh
bash commands/runWith500Slices.sh
bash commands/runWith1000Slices.sh
